version: '2.1'

networks:
  kommonitor:
    name: kommonitor-network

services:

  kommonitor-db:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=kommonitor
      - POSTGRES_PASSWORD=SoTj[5Ss<Df<68r90HE>
      - POSTGRES_DB=kommonitor_data
    volumes:
      - /var/lib/postgresql/data
    networks:
      - kommonitor      
#    healthcheck:
#      test: "exit 0"      

  kommonitor-data-management-api:
    build: .
    image: kommonitor-data-management
    container_name: kommonitor-data-management
    depends_on:
      kommonitor-db:
        condition: service_started
#      geoserver:
 #       condition: service_healthy
    ports:
      - "8085:8085"
    networks:
      - kommonitor      
    links:
      - kommonitor-db
    environment:
     - DATABASE_HOST=kommonitor-db
     - DATABASE_USER=kommonitor
     - DATABASE_PASSWORD=SoTj[5Ss<Df<68r90HE>
     - DATABASE_NAME=kommonitor_data
     - DATABASE_PORT=5432
     - DB_SCHEMA_SPATIALUNITS=public
     - DB_SCHEMA_GEORESOURCES=public
     - DB_SCHEMA_INDICATORS=public
     - ENABLE_OGC_PUBLISHMENT=true
     - GEOSERVER_HOST=geoserver
     - GEOSERVER_PORT=8080
     - GEOSERVER_USER=admin
     - GEOSERVER_PASSWORD=geoserver
     - GEOSERVER_TARGET_WORKSPACE=kommonitor
     - GEOSERVER_DATASTORE_SPATIALUNITS=kommonitor_spatialunits
     - GEOSERVER_DATASTORE_GEORESOURCES=kommonitor_georesources
     - GEOSERVER_DATASTORE_INDICATORS=kommonitor_indicators
     - GEOSERVER_DEFAULT_EPSG=EPSG:4326