--
-- PostgreSQL database dump
--

-- Dumped from database version 10.0
-- Dumped by pg_dump version 11.5

-- Started on 2019-09-12 17:05:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS kommonitor_db;
--
-- TOC entry 6029 (class 1262 OID 309332)
-- Name: kommonitor_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE kommonitor_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'German_Germany.1252' LC_CTYPE = 'German_Germany.1252';


ALTER DATABASE kommonitor_db OWNER TO postgres;

\connect kommonitor_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 309333)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 6030 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry, geography, and raster spatial types and functions';


SET default_tablespace = '';

SET default_with_oids = false;


--
-- TOC entry 500 (class 1259 OID 312214)
-- Name: defaultclassificationmappingitems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.defaultclassificationmappingitems (
    mappingid character varying(255) NOT NULL,
    defaultcolorashex character varying(255),
    defaultcustomrating character varying(255),
    associatedindicatormetadata_datasetid character varying(255)
);


ALTER TABLE public.defaultclassificationmappingitems OWNER TO postgres;

--
-- TOC entry 501 (class 1259 OID 312220)
-- Name: georesourcereference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.georesourcereference (
    entryid character varying(255) NOT NULL,
    mainindicatorid character varying(255),
    referencedescription text,
    referencedgeoresourceid character varying(255)
);


ALTER TABLE public.georesourcereference OWNER TO postgres;

--
-- TOC entry 502 (class 1259 OID 312226)
-- Name: gt_pk_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gt_pk_metadata (
    table_schema character varying(32) NOT NULL,
    table_name character varying(32) NOT NULL,
    pk_column character varying(32) NOT NULL,
    pk_column_idx integer,
    pk_policy character varying(32),
    pk_sequence character varying(64),
    CONSTRAINT gt_pk_metadata_pk_policy_check CHECK (((pk_policy)::text = ANY (ARRAY[('sequence'::character varying)::text, ('assigned'::character varying)::text, ('autogenerated'::character varying)::text])))
);


ALTER TABLE public.gt_pk_metadata OWNER TO postgres;

--
-- TOC entry 503 (class 1259 OID 312230)
-- Name: indicator_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.indicator_tags (
    dataset_id character varying(255) NOT NULL,
    tag character varying(255)
);


ALTER TABLE public.indicator_tags OWNER TO postgres;

--
-- TOC entry 504 (class 1259 OID 312236)
-- Name: indicatorreference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.indicatorreference (
    entryid character varying(255) NOT NULL,
    indicatorid character varying(255),
    referencedescription text,
    referencedindicatorid character varying(255)
);


ALTER TABLE public.indicatorreference OWNER TO postgres;

--
-- TOC entry 505 (class 1259 OID 312242)
-- Name: indicatorspatialunits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.indicatorspatialunits (
    entryid character varying(255) NOT NULL,
    defaultstylename character varying(255),
    indicatormetadataid character varying(255),
    indicatorname character varying(255),
    indicatorvaluetablename character varying(255),
    spatialunitid character varying(255),
    spatialunitname character varying(255),
    wfsurl character varying(255),
    wmsurl character varying(255)
);


ALTER TABLE public.indicatorspatialunits OWNER TO postgres;

--
-- TOC entry 506 (class 1259 OID 312248)
-- Name: metadatageoresources; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metadatageoresources (
    datasetid character varying(255) NOT NULL,
    contact text,
    datasource text,
    datasetname character varying(255),
    dbtablename character varying(255),
    description text,
    jsonschema text,
    lastupdate timestamp with time zone,
    updateintervall character varying(255),
    wfsurl character varying(255),
    wmsurl character varying(255),
    sridepsg integer NOT NULL,
    ispoi boolean DEFAULT false,
    poisymbolbootstrap3name text,
    poimarkercolor integer,
    poisymbolcolor integer,
    databasis character varying,
    note character varying,
    literature character varying
);


ALTER TABLE public.metadatageoresources OWNER TO postgres;

--
-- TOC entry 507 (class 1259 OID 312255)
-- Name: metadatageoresources_topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metadatageoresources_topics (
    dataset_id character varying(255) NOT NULL,
    topic_id character varying(255) NOT NULL
);


ALTER TABLE public.metadatageoresources_topics OWNER TO postgres;

--
-- TOC entry 508 (class 1259 OID 312261)
-- Name: metadataindicators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metadataindicators (
    datasetid character varying(255) NOT NULL,
    contact text,
    datasource text,
    datasetname character varying(255),
    dbtablename character varying(255),
    description text,
    jsonschema text,
    lastupdate timestamp with time zone,
    updateintervall character varying(255),
    wfsurl character varying(255),
    wmsurl character varying(255),
    colorbrewerschemename character varying(255),
    creationtype integer,
    indicatortype integer,
    lowestspatialunitforcomputation character varying(255),
    processdescription text,
    unit character varying(255),
    databasis character varying,
    note character varying,
    abbreviation character varying,
    interpretation character varying,
    isheadlineindicator boolean DEFAULT false,
    literature character varying
);


ALTER TABLE public.metadataindicators OWNER TO postgres;

--
-- TOC entry 509 (class 1259 OID 312268)
-- Name: metadataindicators_defaultclassificationmapping; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metadataindicators_defaultclassificationmapping (
    dataset_id character varying(255) NOT NULL,
    mapping_id character varying(255) NOT NULL
);


ALTER TABLE public.metadataindicators_defaultclassificationmapping OWNER TO postgres;

--
-- TOC entry 510 (class 1259 OID 312274)
-- Name: metadataindicators_topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metadataindicators_topics (
    dataset_id character varying(255) NOT NULL,
    topic_id character varying(255) NOT NULL
);


ALTER TABLE public.metadataindicators_topics OWNER TO postgres;

--
-- TOC entry 511 (class 1259 OID 312280)
-- Name: metadataspatialunits; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metadataspatialunits (
    datasetid character varying(255) NOT NULL,
    contact text,
    datasource text,
    datasetname character varying(255),
    dbtablename character varying(255),
    description text,
    jsonschema text,
    lastupdate timestamp with time zone,
    updateintervall character varying(255),
    wfsurl character varying(255),
    wmsurl character varying(255),
    nextlowerhierarchylevel character varying(255),
    nextupperhierarchylevel character varying(255),
    sridepsg integer NOT NULL,
    databasis character varying,
    note character varying,
    literature character varying
);


ALTER TABLE public.metadataspatialunits OWNER TO postgres;

--
-- TOC entry 512 (class 1259 OID 312286)
-- Name: privileges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.privileges (
    privilegeid character varying(255) NOT NULL,
    privilegename character varying(255)
);


ALTER TABLE public.privileges OWNER TO postgres;

--
-- TOC entry 513 (class 1259 OID 312292)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    roleid character varying(255) NOT NULL,
    rolename character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 514 (class 1259 OID 312298)
-- Name: roles_privileges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles_privileges (
    role_id character varying(255) NOT NULL,
    privilege_id character varying(255) NOT NULL
);


ALTER TABLE public.roles_privileges OWNER TO postgres;

--
-- TOC entry 515 (class 1259 OID 312304)
-- Name: scriptinputparameters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scriptinputparameters (
    inputparameterid character varying(255) NOT NULL,
    datatype integer,
    defaultvalue character varying(255),
    description character varying(255),
    maxparametervaluefornumericinputs double precision NOT NULL,
    minparametervaluefornumericinputs double precision NOT NULL,
    name character varying(255)
);


ALTER TABLE public.scriptinputparameters OWNER TO postgres;

--
-- TOC entry 516 (class 1259 OID 312310)
-- Name: scriptmetadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scriptmetadata (
    scriptid character varying(255) NOT NULL,
    description text,
    indicatorid character varying(255),
    lastupdate timestamp with time zone,
    name character varying(255),
    scriptcode bytea
);


ALTER TABLE public.scriptmetadata OWNER TO postgres;

--
-- TOC entry 517 (class 1259 OID 312316)
-- Name: scripts_inputparameters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scripts_inputparameters (
    script_id character varying(255) NOT NULL,
    inputparameter_id character varying(255) NOT NULL
);


ALTER TABLE public.scripts_inputparameters OWNER TO postgres;

--
-- TOC entry 518 (class 1259 OID 312322)
-- Name: scripts_requiredgeoresources; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scripts_requiredgeoresources (
    script_id character varying(255) NOT NULL,
    dataset_id character varying(255) NOT NULL
);


ALTER TABLE public.scripts_requiredgeoresources OWNER TO postgres;

--
-- TOC entry 519 (class 1259 OID 312328)
-- Name: scripts_requiredindicators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scripts_requiredindicators (
    script_id character varying(255) NOT NULL,
    dataset_id character varying(255) NOT NULL
);


ALTER TABLE public.scripts_requiredindicators OWNER TO postgres;


--
-- TOC entry 623 (class 1259 OID 312540)
-- Name: topics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topics (
    topicid character varying(255) NOT NULL,
    topicdescription text,
    topicname character varying(255)
);


ALTER TABLE public.topics OWNER TO postgres;

--
-- TOC entry 624 (class 1259 OID 312546)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    userid character varying(255) NOT NULL,
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 625 (class 1259 OID 312552)
-- Name: users_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_roles (
    user_id character varying(255) NOT NULL,
    role_id character varying(255) NOT NULL
);


ALTER TABLE public.users_roles OWNER TO postgres;


--
-- TOC entry 5728 (class 2606 OID 314769)
-- Name: defaultclassificationmappingitems defaultclassificationmappingitems_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defaultclassificationmappingitems
    ADD CONSTRAINT defaultclassificationmappingitems_pkey PRIMARY KEY (mappingid);


--
-- TOC entry 5730 (class 2606 OID 314771)
-- Name: georesourcereference georesourcereference_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.georesourcereference
    ADD CONSTRAINT georesourcereference_pkey PRIMARY KEY (entryid);


--
-- TOC entry 5732 (class 2606 OID 314773)
-- Name: gt_pk_metadata gt_pk_metadata_table_schema_table_name_pk_column_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gt_pk_metadata
    ADD CONSTRAINT gt_pk_metadata_table_schema_table_name_pk_column_key UNIQUE (table_schema, table_name, pk_column);


--
-- TOC entry 5734 (class 2606 OID 314775)
-- Name: indicatorreference indicatorreference_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.indicatorreference
    ADD CONSTRAINT indicatorreference_pkey PRIMARY KEY (entryid);


--
-- TOC entry 5736 (class 2606 OID 314777)
-- Name: indicatorspatialunits indicatorspatialunits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.indicatorspatialunits
    ADD CONSTRAINT indicatorspatialunits_pkey PRIMARY KEY (entryid);


--
-- TOC entry 5738 (class 2606 OID 314779)
-- Name: metadatageoresources metadatageoresources_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadatageoresources
    ADD CONSTRAINT metadatageoresources_pkey PRIMARY KEY (datasetid);


--
-- TOC entry 5740 (class 2606 OID 314781)
-- Name: metadataindicators metadataindicators_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadataindicators
    ADD CONSTRAINT metadataindicators_pkey PRIMARY KEY (datasetid);


--
-- TOC entry 5744 (class 2606 OID 314783)
-- Name: metadataspatialunits metadataspatialunits_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadataspatialunits
    ADD CONSTRAINT metadataspatialunits_pkey PRIMARY KEY (datasetid);


--
-- TOC entry 5746 (class 2606 OID 314785)
-- Name: privileges privileges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.privileges
    ADD CONSTRAINT privileges_pkey PRIMARY KEY (privilegeid);


--
-- TOC entry 5748 (class 2606 OID 314787)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (roleid);


--
-- TOC entry 5750 (class 2606 OID 314789)
-- Name: scriptinputparameters scriptinputparameters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scriptinputparameters
    ADD CONSTRAINT scriptinputparameters_pkey PRIMARY KEY (inputparameterid);


--
-- TOC entry 5752 (class 2606 OID 314791)
-- Name: scriptmetadata scriptmetadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scriptmetadata
    ADD CONSTRAINT scriptmetadata_pkey PRIMARY KEY (scriptid);


--
-- TOC entry 5754 (class 2606 OID 314793)
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (topicid);


--
-- TOC entry 5742 (class 2606 OID 314928)
-- Name: metadataindicators_defaultclassificationmapping uk_r7r7bnecj9nd2bqoqbrm5w7qu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadataindicators_defaultclassificationmapping
    ADD CONSTRAINT uk_r7r7bnecj9nd2bqoqbrm5w7qu UNIQUE (mapping_id);


--
-- TOC entry 5756 (class 2606 OID 314797)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (userid);


--
-- TOC entry 5771 (class 2606 OID 314818)
-- Name: scripts_requiredindicators fk1i8b0onfvo84rvlcsk9ct2qgy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scripts_requiredindicators
    ADD CONSTRAINT fk1i8b0onfvo84rvlcsk9ct2qgy FOREIGN KEY (script_id) REFERENCES public.scriptmetadata(scriptid);


--
-- TOC entry 5759 (class 2606 OID 314823)
-- Name: metadatageoresources_topics fk23k8apds0pgebo2318cdcxalo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadatageoresources_topics
    ADD CONSTRAINT fk23k8apds0pgebo2318cdcxalo FOREIGN KEY (topic_id) REFERENCES public.topics(topicid);


--
-- TOC entry 5760 (class 2606 OID 314828)
-- Name: metadatageoresources_topics fk2mcm7g6o1h7wbdd10nxugjxyc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadatageoresources_topics
    ADD CONSTRAINT fk2mcm7g6o1h7wbdd10nxugjxyc FOREIGN KEY (dataset_id) REFERENCES public.metadatageoresources(datasetid);


--
-- TOC entry 5763 (class 2606 OID 314833)
-- Name: metadataindicators_topics fk49mehp3oflfsi4srdpytqtbdl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadataindicators_topics
    ADD CONSTRAINT fk49mehp3oflfsi4srdpytqtbdl FOREIGN KEY (dataset_id) REFERENCES public.metadataindicators(datasetid);


--
-- TOC entry 5769 (class 2606 OID 314838)
-- Name: scripts_requiredgeoresources fk5ml1rn4axdld687al3cwy915o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scripts_requiredgeoresources
    ADD CONSTRAINT fk5ml1rn4axdld687al3cwy915o FOREIGN KEY (dataset_id) REFERENCES public.metadatageoresources(datasetid);


--
-- TOC entry 5767 (class 2606 OID 314843)
-- Name: scripts_inputparameters fk76tojnk9a13moulj92abwtoie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scripts_inputparameters
    ADD CONSTRAINT fk76tojnk9a13moulj92abwtoie FOREIGN KEY (script_id) REFERENCES public.scriptmetadata(scriptid);


--
-- TOC entry 5772 (class 2606 OID 314848)
-- Name: scripts_requiredindicators fka5k490rs0ck8ba60311vcw2ff; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scripts_requiredindicators
    ADD CONSTRAINT fka5k490rs0ck8ba60311vcw2ff FOREIGN KEY (dataset_id) REFERENCES public.metadataindicators(datasetid);


--
-- TOC entry 5758 (class 2606 OID 314853)
-- Name: indicator_tags fkapilr4sy9fst78wiee6iy0oh2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.indicator_tags
    ADD CONSTRAINT fkapilr4sy9fst78wiee6iy0oh2 FOREIGN KEY (dataset_id) REFERENCES public.metadataindicators(datasetid);


--
-- TOC entry 5773 (class 2606 OID 314858)
-- Name: users_roles fkd7cnvrrg9medric9br3dty68; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkd7cnvrrg9medric9br3dty68 FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- TOC entry 5774 (class 2606 OID 314863)
-- Name: users_roles fkeslf2i3y7f123o0cx4rycjtpi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkeslf2i3y7f123o0cx4rycjtpi FOREIGN KEY (role_id) REFERENCES public.roles(roleid);


--
-- TOC entry 5765 (class 2606 OID 314868)
-- Name: roles_privileges fkgsjp8kjx8cdjn84nfi3txdo41; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_privileges
    ADD CONSTRAINT fkgsjp8kjx8cdjn84nfi3txdo41 FOREIGN KEY (privilege_id) REFERENCES public.privileges(privilegeid);


--
-- TOC entry 5768 (class 2606 OID 314873)
-- Name: scripts_inputparameters fkhvw7wqyhrcb6y2ymf6do9yquv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scripts_inputparameters
    ADD CONSTRAINT fkhvw7wqyhrcb6y2ymf6do9yquv FOREIGN KEY (inputparameter_id) REFERENCES public.scriptinputparameters(inputparameterid);


--
-- TOC entry 5770 (class 2606 OID 314878)
-- Name: scripts_requiredgeoresources fkm2lpv28s8utghc3079dobulhk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scripts_requiredgeoresources
    ADD CONSTRAINT fkm2lpv28s8utghc3079dobulhk FOREIGN KEY (script_id) REFERENCES public.scriptmetadata(scriptid);


--
-- TOC entry 5757 (class 2606 OID 314883)
-- Name: defaultclassificationmappingitems fknetb3p2j6vppdhlexpycdj3he; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.defaultclassificationmappingitems
    ADD CONSTRAINT fknetb3p2j6vppdhlexpycdj3he FOREIGN KEY (associatedindicatormetadata_datasetid) REFERENCES public.metadataindicators(datasetid);


--
-- TOC entry 5764 (class 2606 OID 314888)
-- Name: metadataindicators_topics fkpndntlwjkqicphrfdxl9lmgg9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadataindicators_topics
    ADD CONSTRAINT fkpndntlwjkqicphrfdxl9lmgg9 FOREIGN KEY (topic_id) REFERENCES public.topics(topicid);


--
-- TOC entry 5761 (class 2606 OID 314893)
-- Name: metadataindicators_defaultclassificationmapping fkqelnc9v6qm8di2e9t41nkpl0o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadataindicators_defaultclassificationmapping
    ADD CONSTRAINT fkqelnc9v6qm8di2e9t41nkpl0o FOREIGN KEY (dataset_id) REFERENCES public.metadataindicators(datasetid);


--
-- TOC entry 5766 (class 2606 OID 314898)
-- Name: roles_privileges fkt0phdkp5e1r2uvmkbrir5qslr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_privileges
    ADD CONSTRAINT fkt0phdkp5e1r2uvmkbrir5qslr FOREIGN KEY (role_id) REFERENCES public.roles(roleid);


--
-- TOC entry 5762 (class 2606 OID 314903)
-- Name: metadataindicators_defaultclassificationmapping fktohsyfr0y3tihb4irt0jlpkdv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metadataindicators_defaultclassificationmapping
    ADD CONSTRAINT fktohsyfr0y3tihb4irt0jlpkdv FOREIGN KEY (mapping_id) REFERENCES public.defaultclassificationmappingitems(mappingid);


-- Completed on 2019-09-12 17:05:26

--
-- PostgreSQL database dump complete
--

