version: '3.8'

networks:
  kommonitor:
    name: kommonitor
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./realms/realm-export.json:/opt/keycloak/data/import/realm.json
      - ./storage/keycloak-db/data:/opt/keycloak/data/h2
    command:
      - start-dev
      - --import-realm
      - --features=admin-fine-grained-authz
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - kommonitor
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
  kommonitor-db:
    image: postgis/postgis:latest
    container_name: kommonitor-db
    restart: unless-stopped
    networks:
      - kommonitor
    ports:
      - 5432:5432
    volumes:
      - ./storage/kommonitor-db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kommonitor
  kommonitor-proxy:
    image: nginx:latest
    container_name: kommonitor-proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_PORT=80
      - DATA_MANAGEMENT=host.docker.internal:8085
    networks:
      - kommonitor

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8083:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@kommonitor.de
      - PGADMIN_DEFAULT_PASSWORD=kommonitor
    volumes:
      - ./storage/pgadmin:/var/lib/pgadmin
    networks:
      - kommonitor
