/**
 * NOTE: This class is auto generated by the swagger code generator program (unset).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.hsbo.kommonitor.datamanagement.api;

import java.security.Principal;
import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.hsbo.kommonitor.datamanagement.model.scripts.ProcessScriptOverviewType;
import de.hsbo.kommonitor.datamanagement.model.scripts.ProcessScriptPOSTInputType;
import de.hsbo.kommonitor.datamanagement.model.scripts.ProcessScriptPUTInputType;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
@javax.annotation.Generated(value = "de.prospectiveharvest.codegen.PHServerGenerator", date = "2018-08-30T06:52:23.226+02:00")

@Api(value = "ProcessScripts", description = "the ProcessScripts API")
public interface ProcessScriptsApi {

    @ApiOperation(value = "Register a new process script", nickname = "addProcessScriptAsBody", notes = "Register a process script associated to a certain indicator", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "API key is missing or invalid"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/process-scripts",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity addProcessScriptAsBody(@ApiParam(value = "details necessary to register the process script" ,required=true )   @RequestBody ProcessScriptPOSTInputType processScriptData);


    @ApiOperation(value = "Delete the process script", nickname = "deleteProcessScript", notes = "Delete the process script associated to the specified indicator", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts/usingIndicatorId/{indicatorId}",
        method = RequestMethod.DELETE)
    ResponseEntity deleteProcessScript(@ApiParam(value = "unique identifier of the selected indicator dataset",required=true) @PathVariable("indicatorId") String indicatorId);


    @ApiOperation(value = "Delete the process script", nickname = "deleteProcessScriptByScriptId", notes = "Delete the process script associated to the specified scriptId", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts/{scriptId}",
        method = RequestMethod.DELETE)
    ResponseEntity deleteProcessScriptByScriptId(@ApiParam(value = "unique identifier of the selected script",required=true) @PathVariable("scriptId") String scriptId);


    @ApiOperation(value = "retrieve the process script code associated to a certain indicator as JavaScript file", nickname = "getProcessScriptCode", notes = "retrieve the process script code associated to a certain indicator as JavaScript file", response = byte[].class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = byte[].class),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts/{scriptId}/scriptCode",
        produces = { "application/javascript" }, 
        method = RequestMethod.GET)
    ResponseEntity<byte[]> getProcessScriptCode(@ApiParam(value = "unique identifier of the selected script",required=true) @PathVariable("scriptId") String scriptId, Principal principal);


    @ApiOperation(value = "retrieve the process script code associated to a certain indicator as JavaScript file", nickname = "getProcessScriptCodeForIndicator", notes = "retrieve the process script code associated to a certain indicator as JavaScript file", response = byte[].class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = byte[].class),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts/usingIndicatorId/{indicatorId}/scriptCode",
        produces = { "application/javascript" }, 
        method = RequestMethod.GET)
    ResponseEntity<byte[]> getProcessScriptCodeForIndicator(@ApiParam(value = "unique identifier of the selected indicator dataset",required=true) @PathVariable("indicatorId") String indicatorId, Principal principal);


    @ApiOperation(value = "retrieve information about the associated process script for a certain indicator", nickname = "getProcessScriptForIndicator", notes = "retrieve information about the associated process script for a certain indicator", response = ProcessScriptOverviewType.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProcessScriptOverviewType.class),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts/usingIndicatorId/{indicatorId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ProcessScriptOverviewType> getProcessScriptForIndicator(@ApiParam(value = "unique identifier of the selected indicator dataset",required=true) @PathVariable("indicatorId") String indicatorId, Principal principal);


    @ApiOperation(value = "retrieve information about the associated process script for a certain scriptId", nickname = "getProcessScriptForScriptId", notes = "retrieve information about the associated process script for a certain scriptId", response = ProcessScriptOverviewType.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProcessScriptOverviewType.class),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts/{scriptId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ProcessScriptOverviewType> getProcessScriptForScriptId(@ApiParam(value = "unique identifier of the selected script",required=true) @PathVariable("scriptId") String scriptId, Principal principal);


    @ApiOperation(value = "retrieve an empty script template, that defines how to implement process scripts for KomMonitor as JavaScript file.", nickname = "getProcessScriptTemplate", notes = "retrieve an empty script template, that defines how to implement process scripts for KomMonitor. The script works as a template for a NodeJS module. Hence, it predefines required methods that are called by the executing processing engine (a NodeJS runtimne environment). As a script developer, those predefined methods have to be implemented. The template contains detailed documentation on how to implement those methods.", response = byte[].class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = byte[].class),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts/template",
        produces = { "application/javascript" }, 
        method = RequestMethod.GET)
    ResponseEntity<byte[]> getProcessScriptTemplate();


    @ApiOperation(value = "retrieve information about available process scripts", nickname = "getProcessScripts", notes = "retrieve information about available process scripts", response = ProcessScriptOverviewType.class, responseContainer = "array", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProcessScriptOverviewType.class, responseContainer = "array"),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/process-scripts",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ProcessScriptOverviewType>> getProcessScripts(Principal principal);


    @ApiOperation(value = "Modify/Update an existing process script", nickname = "updateProcessScriptAsBody", notes = "Modify/Update an existing process script associated to a certain indicator", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 401, message = "API key is missing or invalid"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/process-scripts/usingIndicatorId/{indicatorId}",
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity updateProcessScriptAsBody(@ApiParam(value = "unique identifier of the selected indicator dataset",required=true) @PathVariable("indicatorId") String indicatorId,@ApiParam(value = "details necessary to modify the process script" ,required=true )   @RequestBody ProcessScriptPUTInputType processScriptData);


    @ApiOperation(value = "Modify/Update an existing process script", nickname = "updateProcessScriptAsBodyByScriptId", notes = "Modify/Update an existing process script associated to a certain scriptId", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 401, message = "API key is missing or invalid"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/process-scripts/{scriptId}",
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity updateProcessScriptAsBodyByScriptId(@ApiParam(value = "unique identifier of the selected script",required=true) @PathVariable("scriptId") String scriptId,@ApiParam(value = "details necessary to modify the process script" ,required=true )   @RequestBody ProcessScriptPUTInputType processScriptData);

}
