/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.hsbo.kommonitor.datamanagement.api;

import java.math.BigDecimal;
import org.springframework.lang.Nullable;
import de.hsbo.kommonitor.datamanagement.model.OwnerInputType;
import de.hsbo.kommonitor.datamanagement.model.PermissionLevelInputType;
import de.hsbo.kommonitor.datamanagement.model.PermissionLevelType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitHierarchyInputType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitHierarchyMemberInputType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitHierarchyMembershipInputType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitHierarchyOverviewType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitOverviewType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitPATCHInputType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitPOSTInputType;
import de.hsbo.kommonitor.datamanagement.model.SpatialUnitPUTInputType;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-09-14T14:52:27.526420500+02:00[Europe/Berlin]", comments = "Generator version: 7.23.0")
@Validated
@Tag(name = "spatial-units", description = "the SpatialUnits API")
public interface SpatialUnitsApi {

    String PATH_ADD_SPATIAL_UNIT_AS_BODY = "/spatial-units";
    /**
     * POST /spatial-units : Add a new spatial-unit
     * Add/Register a spatial unit for a certain period of time
     *
     * @param featureData feature data (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addSpatialUnitAsBody",
        summary = "Add a new spatial-unit",
        description = "Add/Register a spatial unit for a certain period of time",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitOverviewType.class))
            }),
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitOverviewType.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SpatialUnitsApi.PATH_ADD_SPATIAL_UNIT_AS_BODY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<SpatialUnitOverviewType> addSpatialUnitAsBody(
        @Parameter(name = "featureData", description = "feature data", required = true) @Valid @RequestBody SpatialUnitPOSTInputType featureData
    );


    String PATH_ADD_SPATIAL_UNIT_HIERARCHY = "/spatial-unit-hierarchies";
    /**
     * POST /spatial-unit-hierarchies : Add a new spatial unit hierarchy
     * Create a new hierarchy owned by a mandant. A mandant may own one or more hierarchies.
     *
     * @param hierarchyData hierarchy definition (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addSpatialUnitHierarchy",
        summary = "Add a new spatial unit hierarchy",
        description = "Create a new hierarchy owned by a mandant. A mandant may own one or more hierarchies.",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitHierarchyOverviewType.class))
            }),
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitHierarchyOverviewType.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SpatialUnitsApi.PATH_ADD_SPATIAL_UNIT_HIERARCHY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<SpatialUnitHierarchyOverviewType> addSpatialUnitHierarchy(
        @Parameter(name = "hierarchyData", description = "hierarchy definition", required = true) @Valid @RequestBody SpatialUnitHierarchyInputType hierarchyData
    );


    String PATH_DELETE_ALL_SPATIAL_UNIT_FEATURES_BY_ID = "/spatial-units/{spatialUnitId}/allFeatures";
    /**
     * DELETE /spatial-units/{spatialUnitId}/allFeatures : Delete all features/contents of the selected spatial-unit dataset
     * Delete all features/contents of the selected spatial-unit dataset
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     */
    @Operation(
        operationId = "deleteAllSpatialUnitFeaturesById",
        summary = "Delete all features/contents of the selected spatial-unit dataset",
        description = "Delete all features/contents of the selected spatial-unit dataset",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SpatialUnitsApi.PATH_DELETE_ALL_SPATIAL_UNIT_FEATURES_BY_ID
    )
    ResponseEntity<Void> deleteAllSpatialUnitFeaturesById(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId
    );


    String PATH_DELETE_SINGLE_SPATIAL_UNIT_FEATURE_BY_ID = "/spatial-units/{spatialUnitId}/singleFeature/{featureId}";
    /**
     * DELETE /spatial-units/{spatialUnitId}/singleFeature/{featureId} : Delete all database records for the specified feature of the selected spatial-unit dataset
     * Delete all database records for the specified feature of the selected spatial-unit dataset
     *
     * @param spatialUnitId the identifier of the spatial-unit dataset (required)
     * @param featureId the identifier of the spatial-unit dataset feature (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     */
    @Operation(
        operationId = "deleteSingleSpatialUnitFeatureById",
        summary = "Delete all database records for the specified feature of the selected spatial-unit dataset",
        description = "Delete all database records for the specified feature of the selected spatial-unit dataset",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SpatialUnitsApi.PATH_DELETE_SINGLE_SPATIAL_UNIT_FEATURE_BY_ID
    )
    ResponseEntity<Void> deleteSingleSpatialUnitFeatureById(
        @Parameter(name = "spatialUnitId", description = "the identifier of the spatial-unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "featureId", description = "the identifier of the spatial-unit dataset feature", required = true, in = ParameterIn.PATH) @PathVariable("featureId") String featureId
    );


    String PATH_DELETE_SINGLE_SPATIAL_UNIT_FEATURE_RECORD_BY_ID = "/spatial-units/{spatialUnitId}/singleFeature/{featureId}/singleFeatureRecord/{featureRecordId}";
    /**
     * DELETE /spatial-units/{spatialUnitId}/singleFeature/{featureId}/singleFeatureRecord/{featureRecordId} : Delete single feature database record specified by its unique database primary key id for the specified feature of the selected spatial-unit dataset
     * Delete single feature database record specified by its unique database primary key id for the specified feature of the selected spatial-unit dataset
     *
     * @param spatialUnitId the identifier of the spatial-unit dataset (required)
     * @param featureId the identifier of the spatial-unit dataset feature (required)
     * @param featureRecordId the unique database record identifier of the spatial-unit dataset feature - multiple records may exist for the same real world object if they apply to different periods of validity (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     */
    @Operation(
        operationId = "deleteSingleSpatialUnitFeatureRecordById",
        summary = "Delete single feature database record specified by its unique database primary key id for the specified feature of the selected spatial-unit dataset",
        description = "Delete single feature database record specified by its unique database primary key id for the specified feature of the selected spatial-unit dataset",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SpatialUnitsApi.PATH_DELETE_SINGLE_SPATIAL_UNIT_FEATURE_RECORD_BY_ID
    )
    ResponseEntity<Void> deleteSingleSpatialUnitFeatureRecordById(
        @Parameter(name = "spatialUnitId", description = "the identifier of the spatial-unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "featureId", description = "the identifier of the spatial-unit dataset feature", required = true, in = ParameterIn.PATH) @PathVariable("featureId") String featureId,
        @Parameter(name = "featureRecordId", description = "the unique database record identifier of the spatial-unit dataset feature - multiple records may exist for the same real world object if they apply to different periods of validity", required = true, in = ParameterIn.PATH) @PathVariable("featureRecordId") String featureRecordId
    );


    String PATH_DELETE_SPATIAL_UNIT_BY_ID = "/spatial-units/{spatialUnitId}";
    /**
     * DELETE /spatial-units/{spatialUnitId} : Delete the features/contents of the selected spatial-unit
     * Delete the features/contents of the selected spatial-unit
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     */
    @Operation(
        operationId = "deleteSpatialUnitById",
        summary = "Delete the features/contents of the selected spatial-unit",
        description = "Delete the features/contents of the selected spatial-unit",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SpatialUnitsApi.PATH_DELETE_SPATIAL_UNIT_BY_ID
    )
    ResponseEntity<Void> deleteSpatialUnitById(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId
    );


    String PATH_DELETE_SPATIAL_UNIT_BY_ID_AND_YEAR_AND_MONTH = "/spatial-units/{spatialUnitId}/{year}/{month}/{day}";
    /**
     * DELETE /spatial-units/{spatialUnitId}/{year}/{month}/{day} : Delete the features/contents of the selected spatial-unit, year and month
     * Delete the features/contents of the selected spatial-unit, year and month
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @param year year for which datasets shall be queried (required)
     * @param month month for which datasets shall be queried (required)
     * @param day day for which datasets shall be queried (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     */
    @Operation(
        operationId = "deleteSpatialUnitByIdAndYearAndMonth",
        summary = "Delete the features/contents of the selected spatial-unit, year and month",
        description = "Delete the features/contents of the selected spatial-unit, year and month",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SpatialUnitsApi.PATH_DELETE_SPATIAL_UNIT_BY_ID_AND_YEAR_AND_MONTH
    )
    ResponseEntity<Void> deleteSpatialUnitByIdAndYearAndMonth(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "year", description = "year for which datasets shall be queried", required = true, in = ParameterIn.PATH) @PathVariable("year") BigDecimal year,
        @Parameter(name = "month", description = "month for which datasets shall be queried", required = true, in = ParameterIn.PATH) @PathVariable("month") BigDecimal month,
        @Parameter(name = "day", description = "day for which datasets shall be queried", required = true, in = ParameterIn.PATH) @PathVariable("day") BigDecimal day
    );


    String PATH_DELETE_SPATIAL_UNIT_HIERARCHY_BY_ID = "/spatial-unit-hierarchies/{hierarchyId}";
    /**
     * DELETE /spatial-unit-hierarchies/{hierarchyId} : Delete a spatial unit hierarchy
     * Delete the selected spatial unit hierarchy. The spatial units that were members of the hierarchy are not deleted.
     *
     * @param hierarchyId the unique identifier of the hierarchy (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     */
    @Operation(
        operationId = "deleteSpatialUnitHierarchyById",
        summary = "Delete a spatial unit hierarchy",
        description = "Delete the selected spatial unit hierarchy. The spatial units that were members of the hierarchy are not deleted.",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SpatialUnitsApi.PATH_DELETE_SPATIAL_UNIT_HIERARCHY_BY_ID
    )
    ResponseEntity<Void> deleteSpatialUnitHierarchyById(
        @Parameter(name = "hierarchyId", description = "the unique identifier of the hierarchy", required = true, in = ParameterIn.PATH) @PathVariable("hierarchyId") String hierarchyId
    );


    String PATH_GET_ALL_SPATIAL_UNIT_FEATURES_BY_ID = "/spatial-units/{spatialUnitId}/allFeatures";
    /**
     * GET /spatial-units/{spatialUnitId}/allFeatures : retrieve all feature entries for all applicable periods of validity for the selected spatial unit/level (hence might contain each feature multiple times if they exist for different periods of validity)
     * retrieve all feature entries for all applicable periods of validity for the selected spatial unit/level (hence might contain each feature multiple times if they exist for different periods of validity)
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @param simplifyGeometries ontrols simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from &#39;weak&#39; to &#39;strong&#39;, while &#39;original&#39; will return original feature geometries without any simplification. (optional, default to original)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getAllSpatialUnitFeaturesById",
        summary = "retrieve all feature entries for all applicable periods of validity for the selected spatial unit/level (hence might contain each feature multiple times if they exist for different periods of validity)",
        description = "retrieve all feature entries for all applicable periods of validity for the selected spatial unit/level (hence might contain each feature multiple times if they exist for different periods of validity)",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = byte[].class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_ALL_SPATIAL_UNIT_FEATURES_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<byte[]> getAllSpatialUnitFeaturesById(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "simplifyGeometries", description = "ontrols simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from 'weak' to 'strong', while 'original' will return original feature geometries without any simplification.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "simplifyGeometries", required = false, defaultValue = "original") String simplifyGeometries
    );


    String PATH_GET_SINGLE_SPATIAL_UNIT_FEATURE_BY_ID = "/spatial-units/{spatialUnitId}/singleFeature/{featureId}";
    /**
     * GET /spatial-units/{spatialUnitId}/singleFeature/{featureId} : retrieve single feature database records for all applicable periods of validity for the selected spatial-unit dataset (hence might contain the target feature multiple times if it exists for different periods of validity)
     * retrieve single feature database records for all applicable periods of validity for the selected spatial-unit dataset (hence might contain the target feature multiple times if it exists for different periods of validity)
     *
     * @param spatialUnitId the identifier of the spatial-unit dataset (required)
     * @param featureId the identifier of the spatial-unit dataset feature (required)
     * @param simplifyGeometries Controls simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from &#39;weak&#39; to &#39;strong&#39;, while &#39;original&#39; will return original feature geometries without any simplification. (optional, default to original)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSingleSpatialUnitFeatureById",
        summary = "retrieve single feature database records for all applicable periods of validity for the selected spatial-unit dataset (hence might contain the target feature multiple times if it exists for different periods of validity)",
        description = "retrieve single feature database records for all applicable periods of validity for the selected spatial-unit dataset (hence might contain the target feature multiple times if it exists for different periods of validity)",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = byte[].class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SINGLE_SPATIAL_UNIT_FEATURE_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<byte[]> getSingleSpatialUnitFeatureById(
        @Parameter(name = "spatialUnitId", description = "the identifier of the spatial-unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "featureId", description = "the identifier of the spatial-unit dataset feature", required = true, in = ParameterIn.PATH) @PathVariable("featureId") String featureId,
        @Parameter(name = "simplifyGeometries", description = "Controls simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from 'weak' to 'strong', while 'original' will return original feature geometries without any simplification.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "simplifyGeometries", required = false, defaultValue = "original") String simplifyGeometries
    );


    String PATH_GET_SINGLE_SPATIAL_UNIT_FEATURE_RECORD_BY_ID = "/spatial-units/{spatialUnitId}/singleFeature/{featureId}/singleFeatureRecord/{featureRecordId}";
    /**
     * GET /spatial-units/{spatialUnitId}/singleFeature/{featureId}/singleFeatureRecord/{featureRecordId} : retrieve single feature database record specified by its unique database primary key id
     * retrieve single feature database record specified by its unique database primary key id
     *
     * @param spatialUnitId the identifier of the spatial-unit dataset (required)
     * @param featureId the identifier of the spatial-unit dataset feature (required)
     * @param featureRecordId the unique database record identifier of the spatial-unit dataset feature - multiple records may exist for the same real world object if they apply to different periods of validity (required)
     * @param simplifyGeometries Controls simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from &#39;weak&#39; to &#39;strong&#39;, while &#39;original&#39; will return original feature geometries without any simplification. (optional, default to original)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSingleSpatialUnitFeatureRecordById",
        summary = "retrieve single feature database record specified by its unique database primary key id",
        description = "retrieve single feature database record specified by its unique database primary key id",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = byte[].class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SINGLE_SPATIAL_UNIT_FEATURE_RECORD_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<byte[]> getSingleSpatialUnitFeatureRecordById(
        @Parameter(name = "spatialUnitId", description = "the identifier of the spatial-unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "featureId", description = "the identifier of the spatial-unit dataset feature", required = true, in = ParameterIn.PATH) @PathVariable("featureId") String featureId,
        @Parameter(name = "featureRecordId", description = "the unique database record identifier of the spatial-unit dataset feature - multiple records may exist for the same real world object if they apply to different periods of validity", required = true, in = ParameterIn.PATH) @PathVariable("featureRecordId") String featureRecordId,
        @Parameter(name = "simplifyGeometries", description = "Controls simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from 'weak' to 'strong', while 'original' will return original feature geometries without any simplification.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "simplifyGeometries", required = false, defaultValue = "original") String simplifyGeometries
    );


    String PATH_GET_SPATIAL_UNIT_HIERARCHIES = "/spatial-unit-hierarchies";
    /**
     * GET /spatial-unit-hierarchies : retrieve the available spatial unit hierarchies
     * retrieve the available spatial unit hierarchies for the mandants the current user is allowed to access
     *
     * @return OK (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSpatialUnitHierarchies",
        summary = "retrieve the available spatial unit hierarchies",
        description = "retrieve the available spatial unit hierarchies for the mandants the current user is allowed to access",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SpatialUnitHierarchyOverviewType.class)))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SPATIAL_UNIT_HIERARCHIES,
        produces = { "application/json" }
    )
    ResponseEntity<List<SpatialUnitHierarchyOverviewType>> getSpatialUnitHierarchies(
        
    );


    String PATH_GET_SPATIAL_UNIT_HIERARCHY_BY_ID = "/spatial-unit-hierarchies/{hierarchyId}";
    /**
     * GET /spatial-unit-hierarchies/{hierarchyId} : retrieve a single spatial unit hierarchy
     * retrieve a single spatial unit hierarchy including its ordered members
     *
     * @param hierarchyId the unique identifier of the hierarchy (required)
     * @return OK (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSpatialUnitHierarchyById",
        summary = "retrieve a single spatial unit hierarchy",
        description = "retrieve a single spatial unit hierarchy including its ordered members",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitHierarchyOverviewType.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SPATIAL_UNIT_HIERARCHY_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<SpatialUnitHierarchyOverviewType> getSpatialUnitHierarchyById(
        @Parameter(name = "hierarchyId", description = "the unique identifier of the hierarchy", required = true, in = ParameterIn.PATH) @PathVariable("hierarchyId") String hierarchyId
    );


    String PATH_GET_SPATIAL_UNITS = "/spatial-units";
    /**
     * GET /spatial-units : retrieve information about available features of different spatial units/levels
     * retrieve information about available features of different spatial units/levels
     *
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSpatialUnits",
        summary = "retrieve information about available features of different spatial units/levels",
        description = "retrieve information about available features of different spatial units/levels",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SpatialUnitOverviewType.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SPATIAL_UNITS,
        produces = { "application/json" }
    )
    ResponseEntity<List<SpatialUnitOverviewType>> getSpatialUnits(
        
    );


    String PATH_GET_SPATIAL_UNITS_BY_ID = "/spatial-units/{spatialUnitId}";
    /**
     * GET /spatial-units/{spatialUnitId} : retrieve information about available features of the selected spatial unit/level
     * retrieve information about available features of the selected spatial unit/level
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSpatialUnitsById",
        summary = "retrieve information about available features of the selected spatial unit/level",
        description = "retrieve information about available features of the selected spatial unit/level",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitOverviewType.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SPATIAL_UNITS_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<SpatialUnitOverviewType> getSpatialUnitsById(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId
    );


    String PATH_GET_SPATIAL_UNITS_BY_ID_AND_YEAR_AND_MONTH = "/spatial-units/{spatialUnitId}/{year}/{month}/{day}";
    /**
     * GET /spatial-units/{spatialUnitId}/{year}/{month}/{day} : retrieve the features according to the selected spatial unit/level and selected year and month as GeoJSON
     * retrieve the features according to the selected spatial unit/level and selected year and month as GeoJSON
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @param year year for which datasets shall be queried (required)
     * @param month month for which datasets shall be queried (required)
     * @param day day for which datasets shall be queried (required)
     * @param simplifyGeometries Controls simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from &#39;weak&#39; to &#39;strong&#39;, while &#39;original&#39; will return original feature geometries without any simplification. (optional, default to original)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSpatialUnitsByIdAndYearAndMonth",
        summary = "retrieve the features according to the selected spatial unit/level and selected year and month as GeoJSON",
        description = "retrieve the features according to the selected spatial unit/level and selected year and month as GeoJSON",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/octed-stream", schema = @Schema(implementation = byte[].class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SPATIAL_UNITS_BY_ID_AND_YEAR_AND_MONTH,
        produces = { "application/octed-stream" }
    )
    ResponseEntity<byte[]> getSpatialUnitsByIdAndYearAndMonth(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "year", description = "year for which datasets shall be queried", required = true, in = ParameterIn.PATH) @PathVariable("year") BigDecimal year,
        @Parameter(name = "month", description = "month for which datasets shall be queried", required = true, in = ParameterIn.PATH) @PathVariable("month") BigDecimal month,
        @Parameter(name = "day", description = "day for which datasets shall be queried", required = true, in = ParameterIn.PATH) @PathVariable("day") BigDecimal day,
        @Parameter(name = "simplifyGeometries", description = "Controls simplification of feature geometries. Each option will preserve topology to neighbour features. Simplification increases from 'weak' to 'strong', while 'original' will return original feature geometries without any simplification.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "simplifyGeometries", required = false, defaultValue = "original") String simplifyGeometries
    );


    String PATH_GET_SPATIAL_UNITS_PERMISSIONS_BY_ID = "/spatial-units/{spatialUnitId}/permissions";
    /**
     * GET /spatial-units/{spatialUnitId}/permissions : retrieve information about the permissions for the selected spatial unit dataset
     * retrieve information about the permissions for the selected spatial unit dataset
     *
     * @param spatialUnitId identifier of the spatial unit dataset (required)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSpatialUnitsPermissionsById",
        summary = "retrieve information about the permissions for the selected spatial unit dataset",
        description = "retrieve information about the permissions for the selected spatial unit dataset",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = PermissionLevelType.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SPATIAL_UNITS_PERMISSIONS_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<List<PermissionLevelType>> getSpatialUnitsPermissionsById(
        @Parameter(name = "spatialUnitId", description = "identifier of the spatial unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId
    );


    String PATH_GET_SPATIAL_UNITS_SCHEMA_BY_ID = "/spatial-units/{spatialUnitId}/schema";
    /**
     * GET /spatial-units/{spatialUnitId}/schema : retrieve the JSON schema for the selected spatial unit/level
     * retrieve the JSON schema for the selected spatial unit/level. The JSON schema indicates the property structure of the dataset.
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getSpatialUnitsSchemaById",
        summary = "retrieve the JSON schema for the selected spatial unit/level",
        description = "retrieve the JSON schema for the selected spatial unit/level. The JSON schema indicates the property structure of the dataset.",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SpatialUnitsApi.PATH_GET_SPATIAL_UNITS_SCHEMA_BY_ID,
        produces = { "application/json" }
    )
    ResponseEntity<String> getSpatialUnitsSchemaById(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId
    );


    String PATH_UPDATE_SPATIAL_UNIT_AS_BODY = "/spatial-units/{spatialUnitId}";
    /**
     * PUT /spatial-units/{spatialUnitId} : Modify/Update the features of the selected spatial-unit
     * Modify/Update the features of the selected spatial-unit. The interface expects a full upload of all geometries for the spatial unit. Internally, those geometries are compared to the existing ones to mark &#39;old&#39; geometries that are no longer in use as outdated. Hence, each geometric object is only persisted once and its use is controlled by time validity marks.
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @param featureData feature data (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateSpatialUnitAsBody",
        summary = "Modify/Update the features of the selected spatial-unit",
        description = "Modify/Update the features of the selected spatial-unit. The interface expects a full upload of all geometries for the spatial unit. Internally, those geometries are compared to the existing ones to mark 'old' geometries that are no longer in use as outdated. Hence, each geometric object is only persisted once and its use is controlled by time validity marks.",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNIT_AS_BODY,
        consumes = { "application/json" }
    )
    ResponseEntity<Void> updateSpatialUnitAsBody(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "featureData", description = "feature data", required = true) @Valid @RequestBody SpatialUnitPUTInputType featureData
    );


    String PATH_UPDATE_SPATIAL_UNIT_FEATURE_RECORD_AS_BODY = "/spatial-units/{spatialUnitId}/singleFeature/{featureId}/singleFeatureRecord/{featureRecordId}";
    /**
     * PUT /spatial-units/{spatialUnitId}/singleFeature/{featureId}/singleFeatureRecord/{featureRecordId} : Modify/Update the feature record of the selected spatial-unit dataset feature
     * Modify/Update the feature record of the selected spatial-unit dataset feature
     *
     * @param spatialUnitId the identifier of the spatial-unit dataset (required)
     * @param featureId the identifier of the spatial-unit dataset feature (required)
     * @param featureRecordId the unique database record identifier of the spatial-unit dataset feature - multiple records may exist for the same real world object if they apply to different periods of validity (required)
     * @param spatialUnitFeatureRecordData spatial-unit feature record data (required)
     * @return OK - Updated (status code 200)
     *         or Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateSpatialUnitFeatureRecordAsBody",
        summary = "Modify/Update the feature record of the selected spatial-unit dataset feature",
        description = "Modify/Update the feature record of the selected spatial-unit dataset feature",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK - Updated"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNIT_FEATURE_RECORD_AS_BODY,
        consumes = { "application/json" }
    )
    ResponseEntity<Void> updateSpatialUnitFeatureRecordAsBody(
        @Parameter(name = "spatialUnitId", description = "the identifier of the spatial-unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "featureId", description = "the identifier of the spatial-unit dataset feature", required = true, in = ParameterIn.PATH) @PathVariable("featureId") String featureId,
        @Parameter(name = "featureRecordId", description = "the unique database record identifier of the spatial-unit dataset feature - multiple records may exist for the same real world object if they apply to different periods of validity", required = true, in = ParameterIn.PATH) @PathVariable("featureRecordId") String featureRecordId,
        @Parameter(name = "spatialUnitFeatureRecordData", description = "spatial-unit feature record data", required = true) @Valid @RequestBody String spatialUnitFeatureRecordData
    );


    String PATH_UPDATE_SPATIAL_UNIT_HIERARCHY = "/spatial-unit-hierarchies/{hierarchyId}";
    /**
     * PUT /spatial-unit-hierarchies/{hierarchyId} : Modify/Update a spatial unit hierarchy
     * Modify/Update the metadata (e.g. name) of the selected spatial unit hierarchy
     *
     * @param hierarchyId the unique identifier of the hierarchy (required)
     * @param hierarchyData hierarchy definition (required)
     * @return OK (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateSpatialUnitHierarchy",
        summary = "Modify/Update a spatial unit hierarchy",
        description = "Modify/Update the metadata (e.g. name) of the selected spatial unit hierarchy",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitHierarchyOverviewType.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNIT_HIERARCHY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<SpatialUnitHierarchyOverviewType> updateSpatialUnitHierarchy(
        @Parameter(name = "hierarchyId", description = "the unique identifier of the hierarchy", required = true, in = ParameterIn.PATH) @PathVariable("hierarchyId") String hierarchyId,
        @Parameter(name = "hierarchyData", description = "hierarchy definition", required = true) @Valid @RequestBody SpatialUnitHierarchyInputType hierarchyData
    );


    String PATH_UPDATE_SPATIAL_UNIT_HIERARCHY_MEMBERS = "/spatial-unit-hierarchies/{hierarchyId}/members";
    /**
     * PUT /spatial-unit-hierarchies/{hierarchyId}/members : Set the ordered members of a spatial unit hierarchy
     * Replace the full ordered list of spatial unit members of the selected hierarchy. This single operation covers reordering, removing and adding members within the hierarchy.
     *
     * @param hierarchyId the unique identifier of the hierarchy (required)
     * @param members the ordered list of spatial unit members (required)
     * @return OK (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateSpatialUnitHierarchyMembers",
        summary = "Set the ordered members of a spatial unit hierarchy",
        description = "Replace the full ordered list of spatial unit members of the selected hierarchy. This single operation covers reordering, removing and adding members within the hierarchy.",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitHierarchyOverviewType.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNIT_HIERARCHY_MEMBERS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<SpatialUnitHierarchyOverviewType> updateSpatialUnitHierarchyMembers(
        @Parameter(name = "hierarchyId", description = "the unique identifier of the hierarchy", required = true, in = ParameterIn.PATH) @PathVariable("hierarchyId") String hierarchyId,
        @Parameter(name = "members", description = "the ordered list of spatial unit members", required = true) @Valid @RequestBody List<@Valid SpatialUnitHierarchyMemberInputType> members
    );


    String PATH_UPDATE_SPATIAL_UNIT_HIERARCHY_MEMBERSHIPS = "/spatial-units/{spatialUnitId}/hierarchies";
    /**
     * PUT /spatial-units/{spatialUnitId}/hierarchies : Set the hierarchies a spatial unit belongs to
     * Replace the full set of hierarchy memberships for the selected spatial unit. This single operation covers placing the spatial unit into further hierarchies, changing its level within a hierarchy, and removing it from a hierarchy. All referenced hierarchies must belong to the spatial unit&#39;s mandant.
     *
     * @param spatialUnitId the unique identifier of the spatial unit (required)
     * @param hierarchies the full list of hierarchy memberships for the spatial unit (required)
     * @return OK (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateSpatialUnitHierarchyMemberships",
        summary = "Set the hierarchies a spatial unit belongs to",
        description = "Replace the full set of hierarchy memberships for the selected spatial unit. This single operation covers placing the spatial unit into further hierarchies, changing its level within a hierarchy, and removing it from a hierarchy. All referenced hierarchies must belong to the spatial unit's mandant.",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SpatialUnitOverviewType.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNIT_HIERARCHY_MEMBERSHIPS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<SpatialUnitOverviewType> updateSpatialUnitHierarchyMemberships(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial unit", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "hierarchies", description = "the full list of hierarchy memberships for the spatial unit", required = true) @Valid @RequestBody List<@Valid SpatialUnitHierarchyMembershipInputType> hierarchies
    );


    String PATH_UPDATE_SPATIAL_UNIT_METADATA_AS_BODY = "/spatial-units/{spatialUnitId}";
    /**
     * PATCH /spatial-units/{spatialUnitId} : Modify/Update the metadata of the selected spatial-unit
     * Modify/Update the metadata of the selected spatial-unit. This replaces the formerly stored metadata.
     *
     * @param spatialUnitId the unique identifier of the spatial level (required)
     * @param metadata metadata input (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateSpatialUnitMetadataAsBody",
        summary = "Modify/Update the metadata of the selected spatial-unit",
        description = "Modify/Update the metadata of the selected spatial-unit. This replaces the formerly stored metadata.",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNIT_METADATA_AS_BODY,
        consumes = { "application/json" }
    )
    ResponseEntity<Void> updateSpatialUnitMetadataAsBody(
        @Parameter(name = "spatialUnitId", description = "the unique identifier of the spatial level", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "metadata", description = "metadata input", required = true) @Valid @RequestBody SpatialUnitPATCHInputType metadata
    );


    String PATH_UPDATE_SPATIAL_UNITS_OWNERSHIP = "/spatial-units/{spatialUnitId}/ownership";
    /**
     * PUT /spatial-units/{spatialUnitId}/ownership : update information about the ownership for the selected spatial unit dataset
     * update information about the ownership for the selected spatial unit dataset
     *
     * @param spatialUnitId identifier of the spatial unit dataset (required)
     * @param ownerInputType Spatial unit ownership input. (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "updateSpatialUnitsOwnership",
        summary = "update information about the ownership for the selected spatial unit dataset",
        description = "update information about the ownership for the selected spatial unit dataset",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNITS_OWNERSHIP,
        consumes = { "application/json" }
    )
    ResponseEntity<Void> updateSpatialUnitsOwnership(
        @Parameter(name = "spatialUnitId", description = "identifier of the spatial unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "OwnerInputType", description = "Spatial unit ownership input.", required = true) @Valid @RequestBody OwnerInputType ownerInputType
    );


    String PATH_UPDATE_SPATIAL_UNITS_PERMISSIONS = "/spatial-units/{spatialUnitId}/permissions";
    /**
     * PUT /spatial-units/{spatialUnitId}/permissions : update information about the permissions for the selected spatial unit dataset
     * update information about the permissions for the selected spatial unit dataset
     *
     * @param spatialUnitId identifier of the spatial unit dataset (required)
     * @param permissionLevelInputType Spatial unit permission level input. (required)
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "updateSpatialUnitsPermissions",
        summary = "update information about the permissions for the selected spatial unit dataset",
        description = "update information about the permissions for the selected spatial unit dataset",
        tags = { "spatial-units" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = PermissionLevelType.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SpatialUnitsApi.PATH_UPDATE_SPATIAL_UNITS_PERMISSIONS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<List<PermissionLevelType>> updateSpatialUnitsPermissions(
        @Parameter(name = "spatialUnitId", description = "identifier of the spatial unit dataset", required = true, in = ParameterIn.PATH) @PathVariable("spatialUnitId") String spatialUnitId,
        @Parameter(name = "PermissionLevelInputType", description = "Spatial unit permission level input.", required = true) @Valid @RequestBody PermissionLevelInputType permissionLevelInputType
    );

}
