/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.hsbo.kommonitor.datamanagement.api;

import de.hsbo.kommonitor.datamanagement.model.TopicDisplayOrderInputType;
import de.hsbo.kommonitor.datamanagement.model.TopicDisplayOrderModeInputType;
import de.hsbo.kommonitor.datamanagement.model.TopicInputType;
import de.hsbo.kommonitor.datamanagement.model.TopicOverviewType;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-19T08:43:15.995964500+01:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "topics", description = "the Topics API")
public interface TopicsApi {

    /**
     * POST /topics : Register a new topic
     * Add/Register a topic
     *
     * @param topicData topic input data (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addTopic",
        summary = "Register a new topic",
        description = "Add/Register a topic",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TopicOverviewType.class))
            }),
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TopicOverviewType.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/topics",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<TopicOverviewType> addTopic(
        @Parameter(name = "topicData", description = "topic input data", required = true) @Valid @RequestBody TopicInputType topicData
    );


    /**
     * DELETE /topics/{topicId} : Delete the topic
     * Delete the topic
     *
     * @param topicId unique identifier of the topic (required)
     * @return OK (status code 200)
     *         or No Content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     */
    @Operation(
        operationId = "deleteTopic",
        summary = "Delete the topic",
        description = "Delete the topic",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/topics/{topicId}"
    )
    
    ResponseEntity<Void> deleteTopic(
        @Parameter(name = "topicId", description = "unique identifier of the topic", required = true, in = ParameterIn.PATH) @PathVariable("topicId") String topicId
    );


    /**
     * POST /topics/georesources/display-order : Update display order for submitted georesources main topics
     * Update displayOrder for submitted georesources main topics
     *
     * @param mainGeoresourceTopicOrderArray array of georesource main topic id and display order (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or No Content (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateGeoresourceMainTopicDisplayOrder",
        summary = "Update display order for submitted georesources main topics",
        description = "Update displayOrder for submitted georesources main topics",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/topics/georesources/display-order",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateGeoresourceMainTopicDisplayOrder(
        @Parameter(name = "mainGeoresourceTopicOrderArray", description = "array of georesource main topic id and display order", required = true) @Valid @RequestBody List<@Valid TopicDisplayOrderInputType> mainGeoresourceTopicOrderArray
    );


    /**
     * POST /topics/georesources/display-order/mode : Update the display order mode for georesource topics
     * Update the display order mode for georesource topics
     *
     * @param georesourceTopicOrderMode display order mode for georesource (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or No Content (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateGeoresourcesTopicDisplayOrderMode",
        summary = "Update the display order mode for georesource topics",
        description = "Update the display order mode for georesource topics",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/topics/georesources/display-order/mode",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateGeoresourcesTopicDisplayOrderMode(
        @Parameter(name = "georesourceTopicOrderMode", description = "display order mode for georesource", required = true) @Valid @RequestBody TopicDisplayOrderModeInputType georesourceTopicOrderMode
    );


    /**
     * POST /topics/indicators/display-order : Update display order for submitted indicators main topics
     * Update display order for submitted indicators main topics
     *
     * @param indicatorMainTopicOrderArray array of indicator main topic id and display order (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or No Content (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateIndicatorsMainTopicDisplayOrder",
        summary = "Update display order for submitted indicators main topics",
        description = "Update display order for submitted indicators main topics",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/topics/indicators/display-order",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateIndicatorsMainTopicDisplayOrder(
        @Parameter(name = "indicatorMainTopicOrderArray", description = "array of indicator main topic id and display order", required = true) @Valid @RequestBody List<@Valid TopicDisplayOrderInputType> indicatorMainTopicOrderArray
    );


    /**
     * POST /topics/indicators/display-order/mode : Update the display order mode for indicator topics
     * Update the display order mode for indicator topics
     *
     * @param indicatorTopicOrderMode display order mode for indicators (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or No Content (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateIndicatorsTopicDisplayOrderMode",
        summary = "Update the display order mode for indicator topics",
        description = "Update the display order mode for indicator topics",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/topics/indicators/display-order/mode",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateIndicatorsTopicDisplayOrderMode(
        @Parameter(name = "indicatorTopicOrderMode", description = "display order mode for indicators", required = true) @Valid @RequestBody TopicDisplayOrderModeInputType indicatorTopicOrderMode
    );


    /**
     * PATCH /topics/{topicId}/display-order : Update display order for submitted subtopics
     * Update display order for submitted subtopics
     *
     * @param topicId unique identifier of the topic (required)
     * @param subtopicOrderArray array of subtopic id and display order items (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or No Content (status code 204)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateSubtopicDisplayOrder",
        summary = "Update display order for submitted subtopics",
        description = "Update display order for submitted subtopics",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/topics/{topicId}/display-order",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateSubtopicDisplayOrder(
        @Parameter(name = "topicId", description = "unique identifier of the topic", required = true, in = ParameterIn.PATH) @PathVariable("topicId") String topicId,
        @Parameter(name = "subtopicOrderArray", description = "array of subtopic id and display order items", required = true) @Valid @RequestBody List<@Valid TopicDisplayOrderInputType> subtopicOrderArray
    );


    /**
     * PUT /topics/{topicId} : Modify topic information
     * Modify topic information
     *
     * @param topicId unique identifier of the topic (required)
     * @param topicData topic input data (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "updateTopic",
        summary = "Modify topic information",
        description = "Modify topic information",
        tags = { "topics" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "kommonitor-data-access_oauth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/topics/{topicId}",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateTopic(
        @Parameter(name = "topicId", description = "unique identifier of the topic", required = true, in = ParameterIn.PATH) @PathVariable("topicId") String topicId,
        @Parameter(name = "topicData", description = "topic input data", required = true) @Valid @RequestBody TopicInputType topicData
    );

}
